version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.rails
    container_name: url-shortner-app
    depends_on:     
      - mysql-db
    env_file:
      - ./app.env
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/app:z
    environment:
      RAILS_ENV: development

  mysql-db:
    image: mysql:latest
    container_name: url-shortner-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_ROOT_HOST: '%'